### PR TITLE
Build appstreamcli static

### PR DESCRIPTION
**Pull request by probonopd**
https://github.com/mesonbuild/meson/issues/1715

https://github.com/ximion/appstream/issues/128

### CODE REVIEW

**Comment by probonopd** [comment]
Getting

> /usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: attempted static link of dynamic object `src/libappstream.so.0.12.9'

**Comment by probonopd** [comment]
Now getting
> attempted static link of dynamic object `/usr/lib/libglib-2.0.so'

**Comment by probonopd** [comment]
Now getting

> meson.build:63:0: ERROR: Unknown variable "static".

**Comment by probonopd** [comment]
> meson.build:63:0: ERROR: All keyword arguments must be after positional arguments.

This means that instead of things like

> glib_dep = dependency(static: true, 'glib-2.0', version: '>=2.58')

we probably need 

> glib_dep = dependency('glib-2.0', version: '>=2.58', static: true)

**Comment by probonopd** [comment]
Getting

```
meson.build:63:11: ERROR: Expecting rparen got comma.
('glib-2.0', version : '>=2.54', static: true)
^__________^
```

Why?

**Comment by Tachi107** [comment]
You might want to delete this branch

**Comment by probonopd** [comment]
Indeed. Thanks @Tachi107

**Pull request closed without merging**
