### PR TITLE
Build zsyncmake

### LINKED ISSUE #13: Build zsyncmake
Let's also build `zsyncmake` static because it is used in https://github.com/AppImage/AppImageKit/blob/master/ci/build-appdir.sh

```
wget http://zsync.moria.org.uk/download/zsync-0.6.2.tar.bz2
tar xf zsync-*.tar.bz2
cd zsync-*/
./configure CFLAGS=-no-pie LDFLAGS=-static
make
strip zsync zsyncmake 
```

### PR DESCRIPTION
**Pull request by probonopd**
Closes #13

### CODE REVIEW

**Comment by probonopd** [comment]
Getting `sha1.h:43:43: error: unknown type name 'off_t'` whereas locally (on FreeBSD 13.1) building in this way worked.

Why?

cc @Tachi107

**Comment by Tachi107** [comment]
No idea. Maybe Alpine's libc is incomplete?

**Comment by probonopd** [comment]
Turns out that if you replace `off_t` with `size_t`, then it happily compiles on musl libc.

**Comment by Tachi107** [comment]
@probonopd please note that currently when adding a new binary you need to add it to the `out/` directory in both build.sh and build_chroot.sh. I couldn't come up with a better solution, because you have to run different jobs depending on whether you're running in an emulated environment or not

**Comment by Tachi107** [comment]
Moving them to `out/` in build.sh is for the emulated/containerized build, while moving them in build_chroot.sh is for x86 ones

**Comment by Tachi107** [comment]
And you should also add `--build=<arch>-unknown-linux-musl` to the `./configure` calls, as for some reason it doesn't work (how can autotools be that bad?)

**Comment by Tachi107** [comment]
With `<arch>` I meant "aarch64` etc 😅️

**Comment by probonopd** [comment]
Let's hope that helps against the `configure: error: cannot guess build type; you must specify one`.

**Comment by Tachi107** [comment]
You can probably use `$(uname -m)`

**Comment by Tachi107** [comment]
Passing `$ARCHITECTURE` fails because when piping `build.sh` into `build_chroot.sh` env vars get cleaned up. I don't know how you can pass them to the shell used in the chroot.

https://github.com/probonopd/static-tools/blob/9121b72ccbb2bee913136bc52c76c0510512da09/chroot_build.sh#L24

**Comment by probonopd** [comment]
```
+ ./configure 'CFLAGS=-no-pie' 'LDFLAGS=-static' '--build=x86_64-unknown-linux-musl'
Invalid configuration `x86_64-unknown-linux-musl': machine `x86_64-unknown-linux' not recognized
configure: error: /bin/sh autotools/config.sub x86_64-unknown-linux-musl failed
```

This is frustrating. I know why I like Golang :-)

**Comment by probonopd** [comment]
In [efc6799](https://github.com/probonopd/static-tools/pull/14/commits/efc6799a1f88d0d852439dc4906eb9ea72a08e2b) at least the non-ARM ones were building.

**Comment by Tachi107** [comment]
> ```
> + ./configure 'CFLAGS=-no-pie' 'LDFLAGS=-static' '--build=x86_64-unknown-linux-musl'
> Invalid configuration `x86_64-unknown-linux-musl': machine `x86_64-unknown-linux' not recognized
> configure: error: /bin/sh autotools/config.sub x86_64-unknown-linux-musl failed
> ```
> 
> This is frustrating. I know why I like Golang :-)

I know why I like non-ancient build systems that work (like Meson)...

**Comment by probonopd** [comment]
How confident are you that `x86_64-unknown-linux-musl` is correct? Could it be `=x86_64-linux-musl`?

**Comment by probonopd** [comment]
In the build that worked it [said](https://github.com/probonopd/static-tools/runs/6247017875?check_suite_focus=true#step:3:191):

```
+ ./configure 'CFLAGS=-no-pie' 'LDFLAGS=-static'
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
```

**Comment by Tachi107** [comment]
> How confident are you that `x86_64-unknown-linux-musl` is correct? Could it be `x86_64-linux-musl`?

I don't know autotools well, so I don't know what kind of arch tuple they use. I believe I have seen x86_64-unknown-linux-musl before, but there are also triplets like x86_64-linux-gnu

**Comment by Tachi107** [comment]
> In the build that worked it [said](https://github.com/probonopd/static-tools/runs/6247017875?check_suite_focus=true#step:3:191):
> 
> ```
> + ./configure 'CFLAGS=-no-pie' 'LDFLAGS=-static'
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> ```

-gnu? Strange. What libc does alpine use? I though it used the musl libc, not gnu libc

**Comment by probonopd** [comment]
I think so too!

**Comment by Tachi107** [comment]
This script, last modified 2009-06-10, has failed to recognize
    the operating system you are using. It is advised that you
    download the most up to date version of the config scripts from

**2009**? I now understand why it doesn't work, musl wasn't even a thing

**Comment by Tachi107** [comment]
At this point I think that the `configure` script is too old and must be regenerated.

**Comment by probonopd** [comment]
Whatever - it worked.

What really puzzles me though is why this PR was allowed to upload its artefacts to GitHub Releases. Only builds triggered from the main branch should be allowed to do that.

**Comment by Tachi107** [comment]
> What really puzzles me though is why this PR was allowed to upload its artefacts to GitHub Releases. Only builds triggered from the main branch should be allowed to do that.

Probably because you're running the action from a branch of the same repository. That if should instead be `if: github.event_name != 'pull_request' && github.ref_name == 'master'` or something like that

**Pull request merged**
