### PR TITLE
build static appstreamcli

### PR DESCRIPTION
**Pull request by Tachi107**
Trying to make #5 work

This might be helpful: https://mesonbuild.com/Creating-Linux-binaries.html

### CODE REVIEW

**Comment by Tachi107** [comment]
How can I make the CI run?

**Comment by Tachi107** [comment]
It seems that I've been able to successfully compile appstreamcli statically, see the build logs: https://app.travis-ci.com/github/Tachi107/static-tools/jobs/568746171#L748

`ldd` only reports a dependency on `/lib/ld-musl-aarch64.so.1`, but this is expected, right?

**Comment by probonopd** [comment]
Wow, that would be quite the achievement! Now we need to get this stuff to [build again](https://github.com/probonopd/static-tools/issues/8)...

**Comment by probonopd** [comment]
> ldd only reports a dependency on /lib/ld-musl-aarch64.so.1, but this is expected, right?

What does `file appsreamcli` say`? If it says "static" then we should be fine.

**Comment by Tachi107** [comment]
> Wait, Travis is working (again?) for you?

Yes, but only in my fork. It seems that you've consumed all your free credits. But maybe there's something you can do on Travis' web ui

**Comment by probonopd** [comment]
Let's move to GItHub Actions.

**Comment by Tachi107** [comment]
> Let's move to GItHub Actions.

GitHub only hosts x86-64 runners

**Comment by Tachi107** [comment]
> > ldd only reports a dependency on /lib/ld-musl-aarch64.so.1, but this is expected, right?
> 
> What does `file appsreamcli` say? If it says "static" then we should be fine.

It is now fully static (just needed to add `-no-pie` to `CFLAGS`)



> Let's move to GItHub Actions.

Done

**Comment by probonopd** [comment]
Thanks a lot @Tachi107. Now we need to find a good way of uploading the different architectures to GitHub Releases.

Reference:
https://github.com/softprops/action-gh-release/issues/57

**Comment by Tachi107** [comment]
I forgot to port one last part from Travis to GitHub Actions, these:

https://github.com/probonopd/static-tools/blob/eda9edf025235f272ed1aca27679c65b3907e6bf/.travis.yml#L20-L27

What do they do?

**Comment by probonopd** [comment]
Upload the built binaries to GitHub Releases as downloadable assets:
https://github.com/probonopd/static-tools/releases

**Comment by Tachi107** [comment]
> Upload the built binaries to GitHub Releases as downloadable assets: https://github.com/probonopd/static-tools/releases
> 
> From there our other tools will pick them up.

Do they need to be tagged as "continuous" or can I tag with e.g. the commit date?

**Comment by probonopd** [comment]
`continuous` if you want them to be picked up by the other tools.

**Pull request merged**
