### PR TITLE
ci: complete GitHub Actions transition

### PR DESCRIPTION
**Pull request by Tachi107**
This doesn't seem to work in my fork as I get a 403 HTTP error, but maybe it's just because I'm trying to create releases in a fork/pr.

Could you try merging this to see if it works?

### CODE REVIEW

**Comment by probonopd** [comment]
Fingers crossed!

**Comment by Tachi107** [comment]
It worked! The release message is a bit wrong, but who cares, right?

**Comment by probonopd** [comment]
You DID it. Can't thank you enough. This is awesome! :+1: :+1: :+1:

**Comment by Tachi107** [comment]
Happy to help :)

The only thing missing are builds for arm and arm64...

**Comment by probonopd** [comment]
Watch closely where I am running this build:

```
FreeBSD% cat /etc/os-release 
NAME=FreeBSD
VERSION=13.0-RELEASE-p5
VERSION_ID=13.0
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 13.0-RELEASE-p5"
CPE_NAME=cpe:/o:freebsd:freebsd:13.0
HOME_URL=https://FreeBSD.org/
BUG_REPORT_URL=https://bugs.FreeBSD.org/

FreeBSD% /tmp/appstreamcli-x86_64 --help
Usage:
  appstreamcli-x86_64 [OPTION…] - AppStream CLI.

AppStream command-line interface

Subcommands:
  search TERM      - Search the component database.
  get COMPONENT-ID - Get information about a component by its ID.
  what-provides TYPE VALUE
...
```

**Comment by probonopd** [comment]
> The only thing missing are builds for arm and arm64...

I think it might be doable... 
* https://github.com/uraimo/run-on-arch-action
* https://github.com/jnwatson/py-lmdb/blob/18071c9f11ff153ca04c9c8349523bb877305d19/.github/workflows/python-package.yml#L184

**Comment by Tachi107** [comment]
> Yes, the Linuxulator in FreeBSD happily runs this. How cool is that!

Nice :D

**Comment by Tachi107** [comment]
> > The only thing missing are builds for arm and arm64...
> 
> I think it might be doable...
> 
>     * https://github.com/uraimo/run-on-arch-action
> 
>     * https://github.com/jnwatson/py-lmdb/blob/18071c9f11ff153ca04c9c8349523bb877305d19/.github/workflows/python-package.yml#L184

There's also https://github.com/multiarch/qemu-user-static

**Comment by probonopd** [comment]
Let's continue in https://github.com/probonopd/static-tools/issues/11 :)

**Pull request merged**
